// 5 distinct mock exams based on the structure of real Israeli gifted-children
// entrance exams (end of grade 2 / entry to grade 3).
// Each exam mixes the 3 official sections: verbal, math, shapes (text-based).
// Questions are paraphrased/varied — not copied from any specific test.

export type ExamCategory = 'verbal' | 'math' | 'shapes';

export type ExamQ = {
  id: string;
  category: ExamCategory;
  prompt: string;
  promptEn?: string;
  options: string[];
  optionsEn?: string[];
  correct: number;
  explanation: string;
  explanationEn?: string;
  guidance: string; // step-by-step guidance shown DURING the exam in guided mode
  guidanceEn?: string;
  dir: 'rtl' | 'ltr';
};

export type MockExam = {
  id: string;
  title: string;
  titleEn: string;
  description: string;
  descriptionEn: string;
  questions: ExamQ[];
  timeLimitSec: number;
};

// =============================================================
// Exam 1 — Foundations (verbal-leaning)
// =============================================================
const EXAM_1_QUESTIONS: ExamQ[] = [
  {
    id: 'e1-v1',
    category: 'verbal',
    prompt: 'אֵיזֶה מֵהַבָּאִים שַׁיָּךְ לַקְּבוּצָה: יַתּוּשׁ, חַרְגּוֹל, נְמָלָה?',
    promptEn: 'Which of the following belongs to the group: mosquito, cricket, ant?',
    options: ['סוס ים', 'פרת ים', 'פרת משה רבנו', 'דולפין'],
    optionsEn: ['Seahorse', 'Manatee', 'Ladybug', 'Dolphin'],
    correct: 2,
    explanation: 'יתוש, חרגול ונמלה הם חרקים. פרת משה רבנו (סוג של חיפושית) היא גם חרק. סוס ים הוא דג, פרת ים ודולפין הם יונקים.',
    explanationEn: 'Mosquito, cricket and ant are insects. The ladybug (a beetle) is also an insect. Seahorse is a fish; manatee and dolphin are mammals.',
    guidance: 'שאלת קבוצה: זהה את הכלל המשותף — כל הפריטים הם חרקים. עכשיו חפש בתשובות מי גם חרק.',
    guidanceEn: 'Group question: identify the common rule — all items are insects. Now find which option is also an insect.',
    dir: 'rtl',
  },
  {
    id: 'e1-v2',
    category: 'verbal',
    prompt: 'איזו מהמילים יוצאת דופן?',
    promptEn: 'Which word is the odd one out?',
    options: ['חיפה', 'שדה בוקר', 'ירושלים', 'באר שבע'],
    optionsEn: ['Haifa', 'Sde Boker', 'Jerusalem', 'Beer Sheva'],
    correct: 1,
    explanation: 'חיפה, ירושלים ובאר שבע הן ערים גדולות. שדה בוקר הוא קיבוץ קטן בנגב, לא עיר.',
    explanationEn: 'Haifa, Jerusalem and Beer Sheva are large cities. Sde Boker is a small kibbutz in the Negev, not a city.',
    guidance: 'יוצא דופן: שלוש מהמילים שייכות לאותה קבוצה. מצא את הקטגוריה המשותפת ואז את החריג.',
    guidanceEn: 'Odd one out: three words share a category. Find the shared category, then the exception.',
    dir: 'rtl',
  },
  {
    id: 'e1-v3',
    category: 'verbal',
    prompt: 'מה משמעות הביטוי "אליה וקוץ בה"?',
    promptEn: 'What does the idiom "a tail with a thorn in it" mean?',
    options: ['חדירת קוץ לרגל', 'דבר טוב שיש בו גם פגם', 'תקיפה עם קוץ', 'כתר עשוי קוצים'],
    optionsEn: ['A thorn enters a foot', 'A good thing with a flaw', 'An attack with a thorn', 'A crown of thorns'],
    correct: 1,
    explanation: 'הביטוי מתאר מצב חיובי שיש בו פגם או חסרון מסוים שמפחית מהטוב.',
    explanationEn: 'The idiom describes a positive situation that has a flaw which reduces its goodness.',
    guidance: 'ביטויים: לפעמים יש להם משמעות מטאפורית ולא מילולית. חשוב על המילה "קוץ" — מה היא מסמלת?',
    guidanceEn: 'Idioms: sometimes have metaphorical, not literal meaning. Think what "thorn" symbolizes.',
    dir: 'rtl',
  },
  {
    id: 'e1-v4',
    category: 'verbal',
    prompt: 'איזו מהמילים הפך של "משויף"?',
    promptEn: 'Which is the opposite of "smooth/polished"?',
    options: ['משופע', 'מחוספס', 'חלק', 'מעוקם'],
    optionsEn: ['Sloped', 'Rough', 'Smooth', 'Bent'],
    correct: 1,
    explanation: 'משויף = חלק (שיפשפו אותו והחליקו). ההיפך הוא מחוספס.',
    explanationEn: '"Polished" means smooth (sanded down). The opposite is rough.',
    guidance: 'הפכים: חשוב מה המשמעות של המילה הראשונה, ואז חפש את ההיפך הגמור שלה.',
    guidanceEn: 'Opposites: think about the meaning of the first word, then find its complete opposite.',
    dir: 'rtl',
  },
  {
    id: 'e1-m1',
    category: 'math',
    prompt: 'לרון יש 13 קלפים רגילים ו-5 קלפים זוהרים. לגלית יש 10 רגילים ו-4 זוהרים. אם יאחדו את הכל, כמה קלפים יהיו באוסף המשותף?',
    promptEn: 'Ron has 13 regular cards and 5 shiny cards. Galit has 10 regular and 4 shiny. If they combine, how many in the shared collection?',
    options: ['18', '32', '33', '14'],
    correct: 1,
    explanation: 'רון: 13+5=18. גלית: 10+4=14. ביחד: 18+14=32.',
    explanationEn: "Ron: 13+5=18. Galit: 10+4=14. Together: 18+14=32.",
    guidance: 'חבר את הסכום של רון, אז את הסכום של גלית, ואז חבר את שני הסכומים.',
    guidanceEn: 'Add Ron\'s total, then Galit\'s total, then add the two together.',
    dir: 'rtl',
  },
  {
    id: 'e1-m2',
    category: 'math',
    prompt: 'בגינה של אביתר יש 3 עצי תפוז ו-5 עצי לימון. על כל עץ תפוז יש 8 תפוזים, ועל כל עץ לימון יש 7 לימונים. כמה פירות בגינה?',
    promptEn: "Avitar's garden has 3 orange trees and 5 lemon trees. Each orange tree has 8 oranges, each lemon tree has 7 lemons. How many fruits in total?",
    options: ['59', '62', '43', '14'],
    correct: 0,
    explanation: 'תפוזים: 3×8=24. לימונים: 5×7=35. סה"כ: 24+35=59.',
    explanationEn: 'Oranges: 3×8=24. Lemons: 5×7=35. Total: 24+35=59.',
    guidance: 'בעיה רב-שלבית: כפול עצי תפוז × תפוזים. כפול עצי לימון × לימונים. חבר את שני הסכומים.',
    guidanceEn: 'Multi-step problem: multiply orange trees × oranges, lemon trees × lemons, then add.',
    dir: 'rtl',
  },
  {
    id: 'e1-m3',
    category: 'math',
    prompt: 'בדרך לבית הספר קנתה שרון 3 סוכריות, וכל סוכריה עלתה 3 שקלים. בבית הספר קנתה פחית מיץ ב-5 שקלים. ובדרך חזרה כריך ב-16 שקלים. כמה הוציאה?',
    promptEn: 'On the way to school, Sharon bought 3 candies at 3 NIS each. At school, a juice for 5 NIS. On the way back, a sandwich for 16 NIS. Total spent?',
    options: ['21', '25', '30', '40'],
    correct: 2,
    explanation: 'סוכריות: 3×3=9. סה"כ: 9+5+16=30 ש"ח.',
    explanationEn: 'Candies: 3×3=9. Total: 9+5+16=30 NIS.',
    guidance: 'חשב כל קנייה בנפרד, ואז חבר את הכל ביחד.',
    guidanceEn: 'Calculate each purchase separately, then sum them all up.',
    dir: 'rtl',
  },
  {
    id: 'e1-m4',
    category: 'math',
    prompt: 'רועי בן 6. אמא של רועי גדולה ממנו ב-23 שנים. אבא של רועי קטן מאמא ב-3 שנים. בן כמה אבא של רועי?',
    promptEn: 'Roi is 6. Roi\'s mom is 23 years older than him. Roi\'s dad is 3 years younger than mom. How old is dad?',
    options: ['29', '32', '35', '26'],
    correct: 3,
    explanation: 'אמא: 6+23=29. אבא: 29-3=26.',
    explanationEn: 'Mom: 6+23=29. Dad: 29-3=26.',
    guidance: 'בעיית גילים: קודם חשב גיל אמא, ואז חסר את ההפרש לאבא.',
    guidanceEn: 'Age problem: first calculate mom\'s age, then subtract the difference to get dad\'s age.',
    dir: 'rtl',
  },
  {
    id: 'e1-s1',
    category: 'shapes',
    prompt: 'הסדרה: 🔴 🔵 🔴 🔵 🔴 ?\n\nאיזה צבע יבוא הבא?',
    promptEn: 'Sequence: 🔴 🔵 🔴 🔵 🔴 ?\n\nWhat color comes next?',
    options: ['🟢 ירוק', '🔵 כחול', '🟡 צהוב', '🔴 אדום'],
    optionsEn: ['🟢 Green', '🔵 Blue', '🟡 Yellow', '🔴 Red'],
    correct: 1,
    explanation: 'הדפוס הוא אדום-כחול שחוזר על עצמו. אחרי אדום (האחרון) בא כחול.',
    explanationEn: 'The pattern is red-blue repeating. After the last red comes blue.',
    guidance: 'דפוסי צורות: זהה את החזרה. כאן זה אדום-כחול-אדום-כחול. מה בא אחרי אדום?',
    guidanceEn: 'Shape patterns: identify the repetition. Here it\'s red-blue-red-blue. What comes after red?',
    dir: 'rtl',
  },
  {
    id: 'e1-s2',
    category: 'shapes',
    prompt: 'במשבצות: ⭐ ⭐⭐ ⭐⭐⭐ ?\n\nכמה כוכבים במשבצת הבאה?',
    promptEn: 'In the boxes: ⭐ ⭐⭐ ⭐⭐⭐ ?\n\nHow many stars in the next box?',
    options: ['2 כוכבים', '3 כוכבים', '4 כוכבים', '5 כוכבים'],
    optionsEn: ['2 stars', '3 stars', '4 stars', '5 stars'],
    correct: 2,
    explanation: 'מספר הכוכבים גדל ב-1 כל פעם: 1, 2, 3, ולכן הבא הוא 4.',
    explanationEn: 'The number grows by 1 each step: 1, 2, 3, so next is 4.',
    guidance: 'סדרת כמויות: ספור כמה יש בכל משבצת ומצא את הכלל (כל פעם +1).',
    guidanceEn: 'Quantity sequence: count items per box and find the rule (each step +1).',
    dir: 'rtl',
  },
];

// =============================================================
// Exam 2 — Knowledge & comprehension
// =============================================================
const EXAM_2_QUESTIONS: ExamQ[] = [
  {
    id: 'e2-v1',
    category: 'verbal',
    prompt: 'נקבת הגמל נקראת:',
    promptEn: 'A female camel is called:',
    options: ['גמלה', 'לביאה', 'למה', 'נאקה'],
    optionsEn: ['Gamla', 'Lioness', 'Llama', 'She-camel (naqa)'],
    correct: 3,
    explanation: 'נקבת הגמל בעברית היא נאקה. לביאה היא נקבת האריה, למה היא חיה אחרת לגמרי.',
    explanationEn: 'In Hebrew, a female camel is "naqa". A lioness is the female lion; a llama is a different animal.',
    guidance: 'שאלת ידע: זה משהו שלומדים. אם לא יודעים, נסו לבטל אופציות שאתם בטוחים שלא נכונות.',
    guidanceEn: 'Knowledge question: this is something you learn. If unsure, eliminate options you know are wrong.',
    dir: 'rtl',
  },
  {
    id: 'e2-v2',
    category: 'verbal',
    prompt: 'איזו מהיבשות לא מאוכלסת באנשים באופן קבוע?',
    promptEn: 'Which continent is not permanently inhabited?',
    options: ['אוסטרליה', 'אפריקה', 'אסיה', 'אנטרקטיקה'],
    optionsEn: ['Australia', 'Africa', 'Asia', 'Antarctica'],
    correct: 3,
    explanation: 'אנטרקטיקה היא יבשת הקרח. גרים בה רק חוקרים זמנית.',
    explanationEn: 'Antarctica is the ice continent. Only researchers live there temporarily.',
    guidance: 'שאלת גיאוגרפיה: חשוב על כל יבשת — איפה האקלים הכי קיצוני שאי אפשר לחיות שם?',
    guidanceEn: 'Geography: think about each continent — where is the climate too extreme to live?',
    dir: 'rtl',
  },
  {
    id: 'e2-v3',
    category: 'verbal',
    prompt: 'איזה זוג מילים אינו זוג של נרדפות?',
    promptEn: 'Which pair is NOT synonyms?',
    options: ['שיבה / זקנה', 'מתגעגע / כמה', 'סלידה / רתיעה', 'משקץ / דוקר'],
    optionsEn: ['Old age / elderly', 'Misses / longs for', 'Disgust / aversion', 'Detests / pierces'],
    correct: 3,
    explanation: 'משקץ = מתעב, מואס. דוקר = נועץ משהו חד. אלה שתי משמעויות שונות לחלוטין.',
    explanationEn: '"Detests" means strong dislike; "pierces" means stabbing. Completely different meanings.',
    guidance: 'נרדפות: חפש זוג שבו המילים אומרות דברים שונים, גם אם הן נשמעות דומה.',
    guidanceEn: 'Synonyms: find a pair where the words mean different things, even if they sound similar.',
    dir: 'rtl',
  },
  {
    id: 'e2-v4',
    category: 'verbal',
    prompt: 'דנה הלכה לים והביאה איתה: מגבת, כובע, משקפי שמש. מה עוד שייך לרשימה?',
    promptEn: 'Dana went to the beach and brought: towel, hat, sunglasses. What else fits the list?',
    options: ['מטרייה', 'קרם הגנה', 'מעיל גשם', 'מגפיים'],
    optionsEn: ['Umbrella', 'Sunscreen', 'Raincoat', 'Boots'],
    correct: 1,
    explanation: 'כל הפריטים מגינים מהשמש בים. גם קרם הגנה מגן מהשמש.',
    explanationEn: 'All items protect from sun at the beach. Sunscreen also protects from sun.',
    guidance: 'מצא את הקטגוריה המשותפת — מה תפקיד של כל הפריטים? אז חפש את הפריט שגם ממלא את אותו תפקיד.',
    guidanceEn: 'Find the common category — what do all items do? Then find the option that does the same.',
    dir: 'rtl',
  },
  {
    id: 'e2-m1',
    category: 'math',
    prompt: 'בשמורת הטבע יש 24 איילים שהתחלקו ל-4 קבוצות שוות. כמה איילים בכל קבוצה?',
    promptEn: 'A nature reserve has 24 deer split into 4 equal groups. How many deer per group?',
    options: ['6', '12', '8', '4'],
    correct: 0,
    explanation: '24 ÷ 4 = 6.',
    explanationEn: '24 ÷ 4 = 6.',
    guidance: 'חלוקה שווה: חלק את הסה"כ במספר הקבוצות.',
    guidanceEn: 'Equal sharing: divide the total by the number of groups.',
    dir: 'rtl',
  },
  {
    id: 'e2-m2',
    category: 'math',
    prompt: 'יפתח קיבל ליום הולדתו 9 סוכריות מכל אחד מהאחים שלו. בסך הכל קיבל 45 סוכריות. כמה אחים יש לו?',
    promptEn: 'Yiftach got 9 candies from each sibling for his birthday. Total: 45 candies. How many siblings?',
    options: ['5', '6', '7', '4'],
    correct: 0,
    explanation: '45 ÷ 9 = 5 אחים.',
    explanationEn: '45 ÷ 9 = 5 siblings.',
    guidance: 'בעיה הפוכה לכפל: יודעים את הסה"כ ואת הכמות לכל אחד. חלק כדי למצוא את המספר.',
    guidanceEn: 'Reverse multiplication: you know the total and per-person. Divide to find the count.',
    dir: 'rtl',
  },
  {
    id: 'e2-m3',
    category: 'math',
    prompt: 'מיכאל מקבל 2 ש"ח על כל צלחת ו-1 ש"ח על כל כוס שהוא שוטף. בארוחה היו 20 צלחות ו-30 כוסות. כמה קיבל?',
    promptEn: 'Michael earns 2 NIS per plate and 1 NIS per cup he washes. The meal had 20 plates and 30 cups. How much did he earn?',
    options: ['60', '70', '80', '50'],
    correct: 1,
    explanation: 'צלחות: 20×2=40. כוסות: 30×1=30. סה"כ: 70 ש"ח.',
    explanationEn: 'Plates: 20×2=40. Cups: 30×1=30. Total: 70 NIS.',
    guidance: 'חשב כל סוג בנפרד, ואז חבר.',
    guidanceEn: 'Calculate each type separately, then add them.',
    dir: 'rtl',
  },
  {
    id: 'e2-m4',
    category: 'math',
    prompt: 'לפני שנה ערן היה בן 12. דנה קטנה מערן ב-5 שנים. בת כמה דנה היום?',
    promptEn: 'A year ago Eran was 12. Dana is 5 years younger than Eran. How old is Dana today?',
    options: ['7', '12', '13', '8'],
    correct: 3,
    explanation: 'ערן היום: 12+1=13. דנה: 13-5=8.',
    explanationEn: 'Eran today: 12+1=13. Dana: 13-5=8.',
    guidance: 'גיל בעבר: קודם חשב את הגיל של ערן היום, ואז חשב את גיל דנה ביחס.',
    guidanceEn: 'Past age: first calculate Eran\'s age today, then Dana\'s age relative to him.',
    dir: 'rtl',
  },
  {
    id: 'e2-s1',
    category: 'shapes',
    prompt: 'סדרה: 🔺 🔺🔺 🔺🔺🔺 ?',
    promptEn: 'Sequence: 🔺 🔺🔺 🔺🔺🔺 ?',
    options: ['🔺🔺', '🔺🔺🔺🔺', '🔺🔺🔺', '🔺'],
    optionsEn: ['🔺🔺', '🔺🔺🔺🔺', '🔺🔺🔺', '🔺'],
    correct: 1,
    explanation: 'הסדרה גדלה ב-1 כל פעם: 1, 2, 3, אז הבא הוא 4 משולשים.',
    explanationEn: 'Each step adds 1: 1, 2, 3, so next is 4 triangles.',
    guidance: 'ספור את הצורות בכל קבוצה. מה הכלל?',
    guidanceEn: 'Count shapes in each group. What\'s the rule?',
    dir: 'rtl',
  },
  {
    id: 'e2-s2',
    category: 'shapes',
    prompt: 'דפוס: ⬛⬜⬛⬜⬛⬜?\n\nמה בא הבא?',
    promptEn: 'Pattern: ⬛⬜⬛⬜⬛⬜?\n\nWhat comes next?',
    options: ['⬛', '⬜', '🟦', '🟥'],
    correct: 0,
    explanation: 'הדפוס הוא שחור-לבן שחוזר. אחרי לבן בא שחור.',
    explanationEn: 'Pattern is black-white repeating. After white comes black.',
    guidance: 'דפוס פשוט של 2 צבעים — חפש את הסדר.',
    guidanceEn: 'Simple 2-color pattern — find the order.',
    dir: 'rtl',
  },
];

// =============================================================
// Exam 3 — Word problems focus
// =============================================================
const EXAM_3_QUESTIONS: ExamQ[] = [
  {
    id: 'e3-v1',
    category: 'verbal',
    prompt: 'איזו מהמילים שייכת לקבוצה: נגר, צורף, סנדלר?',
    promptEn: 'Which word belongs to the group: carpenter, jeweler, shoemaker?',
    options: ['תלמיד', 'שען', 'נער', 'אופה'],
    optionsEn: ['Student', 'Watchmaker', 'Boy', 'Baker'],
    correct: 1,
    explanation: 'כולם בעלי מקצוע ידני שיוצרים דברים. גם שען הוא בעל מקצוע ידני.',
    explanationEn: 'All are manual craftspeople who make things. Watchmaker is also a manual craftsperson.',
    guidance: 'מה משותף לכל הפריטים בקבוצה? מצא את הכלל ובדוק איזו אופציה גם מתאימה.',
    guidanceEn: 'What\'s common to all items? Find the rule and check which option also fits.',
    dir: 'rtl',
  },
  {
    id: 'e3-v2',
    category: 'verbal',
    prompt: 'איזו מהבאות שייכת לקבוצה: לקצור, לשתול, להשקות?',
    promptEn: 'Which belongs to the group: to harvest, to plant, to water?',
    options: ['חיות', 'יסודות', 'צמחים', 'אבנים'],
    optionsEn: ['Animals', 'Elements', 'Plants', 'Stones'],
    correct: 2,
    explanation: 'כל הפעולות קשורות לטיפול בצמחים בגינה.',
    explanationEn: 'All actions relate to caring for plants in a garden.',
    guidance: 'הקבוצה מציגה פעולות. שאל את עצמך: למה משתמשים בפעולות האלה?',
    guidanceEn: 'The group shows actions. Ask: what are these actions used for?',
    dir: 'rtl',
  },
  {
    id: 'e3-v3',
    category: 'verbal',
    prompt: 'מה משותף לכוכבי לכת מאדים, צדק, שבתאי?',
    promptEn: 'What do Mars, Jupiter, Saturn have in common?',
    options: ['כולם מטאורים', 'כולם שמשות', 'כולם כוכבי לכת', 'כולם ירחים'],
    optionsEn: ['All meteors', 'All suns', 'All planets', 'All moons'],
    correct: 2,
    explanation: 'מאדים, צדק ושבתאי הם כוכבי לכת במערכת השמש.',
    explanationEn: 'Mars, Jupiter and Saturn are planets in the Solar System.',
    guidance: 'ידע כללי על מערכת השמש.',
    guidanceEn: 'General knowledge about the Solar System.',
    dir: 'rtl',
  },
  {
    id: 'e3-v4',
    category: 'verbal',
    prompt: 'איזו מילה היא בעלת משמעות זהה למילה "לבזוז"?',
    promptEn: 'Which word has the same meaning as "to plunder"?',
    options: ['לבזבז', 'להעריץ', 'לשדוד', 'להחזיר'],
    optionsEn: ['To waste', 'To admire', 'To rob', 'To return'],
    correct: 2,
    explanation: 'לבזוז = לשדוד, לקחת בכוח. לבזבז זה דבר אחר לגמרי (להוציא כסף לחינם).',
    explanationEn: '"Plunder" = to rob, take by force. "Waste" is something different (spending money for nothing).',
    guidance: 'נרדפות: שים לב למילים שנשמעות דומה אבל המשמעות שונה.',
    guidanceEn: 'Synonyms: watch out for similar-sounding words with different meanings.',
    dir: 'rtl',
  },
  {
    id: 'e3-m1',
    category: 'math',
    prompt: 'דורון קופץ בחבל 13 דקות. אביגיל קופצת פי 3 מהזמן של דורון. כמה דקות קופצת אביגיל?',
    promptEn: 'Doron jumps rope for 13 minutes. Avigail jumps for 3 times as long. How many minutes does Avigail jump?',
    options: ['33', '13', '43', '39'],
    correct: 3,
    explanation: '13 × 3 = 39 דקות.',
    explanationEn: '13 × 3 = 39 minutes.',
    guidance: '"פי 3" אומר לכפול ב-3.',
    guidanceEn: '"3 times" means multiply by 3.',
    dir: 'rtl',
  },
  {
    id: 'e3-m2',
    category: 'math',
    prompt: 'אימון אגרוף נמשך 45 דקות. דנה התחילה להתאמן בשעה 1:15. באיזו שעה יסתיים האימון?',
    promptEn: "A boxing workout lasts 45 minutes. Dana started at 1:15. When does it end?",
    options: ['2:00', '2:15', '2:30', '3:00'],
    correct: 0,
    explanation: '1:15 + 45 דקות = 2:00.',
    explanationEn: '1:15 + 45 minutes = 2:00.',
    guidance: 'חבר את הזמן ההתחלתי עם משך האימון. 15+45=60 דקות = שעה שלמה.',
    guidanceEn: 'Add start time + duration. 15+45=60 minutes = one hour.',
    dir: 'rtl',
  },
  {
    id: 'e3-m3',
    category: 'math',
    prompt: 'סוכריה עולה 2 שקלים. כמה עודף מקבלים מ-10 שקלים אם קונים 3 סוכריות?',
    promptEn: 'A candy costs 2 NIS. How much change from 10 NIS if you buy 3 candies?',
    options: ['6', '4', '8', '7'],
    correct: 1,
    explanation: '3 סוכריות × 2 = 6. עודף: 10-6=4 שקלים.',
    explanationEn: '3 × 2 = 6. Change: 10-6 = 4 NIS.',
    guidance: 'קודם חשב כמה עולה הקנייה הכוללת, ואז חסר מהסכום ששילמת.',
    guidanceEn: 'First calculate total cost, then subtract from amount paid.',
    dir: 'rtl',
  },
  {
    id: 'e3-m4',
    category: 'math',
    prompt: 'סבתא נחמה אפתה עוגה וחילקה אותה לפרוסות שוות. רונן אכל שליש מהפרוסות, בסך הכל 4 פרוסות. כמה פרוסות לא אכל רונן?',
    promptEn: 'Grandma Nehama baked a cake into equal slices. Ronen ate one-third — 4 slices in total. How many did he NOT eat?',
    options: ['8', '12', '15', '4'],
    correct: 0,
    explanation: 'אם 4 פרוסות = שליש, אז כל העוגה = 12 פרוסות. רונן לא אכל: 12-4=8.',
    explanationEn: 'If 4 slices = one-third, then full cake = 12 slices. Not eaten: 12-4=8.',
    guidance: 'בעיית שברים: אם שליש הוא 4, חשב כמה זה השלם (כפל ב-3), ואז חסר.',
    guidanceEn: 'Fraction problem: if a third is 4, calculate the whole (multiply by 3), then subtract.',
    dir: 'rtl',
  },
  {
    id: 'e3-s1',
    category: 'shapes',
    prompt: 'דפוס: 🔺🟦 🔺🟦 🔺?\n\nמה חסר?',
    promptEn: 'Pattern: 🔺🟦 🔺🟦 🔺?\n\nWhat is missing?',
    options: ['🔺', '🟦', '🟢', '⭐'],
    correct: 1,
    explanation: 'הדפוס: משולש-ריבוע. אחרי המשולש האחרון בא ריבוע.',
    explanationEn: 'Pattern: triangle-square. After the last triangle comes a square.',
    guidance: 'דפוס של זוגות. מצא את הזוג ושים לב מי תמיד הולך אחרי מי.',
    guidanceEn: 'Pair pattern. Find the pair and note who always follows whom.',
    dir: 'rtl',
  },
  {
    id: 'e3-s2',
    category: 'shapes',
    prompt: 'יש לי 3 קווים בכל פיגורה. ⏃ ⏄ ⏅ — איזו צורה הבאה תתאים?',
    promptEn: 'Each figure has 3 lines. ⏃ ⏄ ⏅ — which next shape fits?',
    options: ['קו אחד', 'משולש (3 קווים)', 'ריבוע (4 קווים)', 'נקודה'],
    optionsEn: ['One line', 'Triangle (3 lines)', 'Square (4 lines)', 'Dot'],
    correct: 1,
    explanation: 'הכלל: כל פיגורה עם 3 קווים. משולש = 3 קווים.',
    explanationEn: 'Rule: every figure has 3 lines. A triangle has 3 lines.',
    guidance: 'מצא את הכלל המשותף ובדוק איזו תשובה גם עומדת בכלל.',
    guidanceEn: 'Find the common rule and check which answer also satisfies it.',
    dir: 'rtl',
  },
];

// =============================================================
// Exam 4 — Vocabulary & advanced math
// =============================================================
const EXAM_4_QUESTIONS: ExamQ[] = [
  {
    id: 'e4-v1',
    category: 'verbal',
    prompt: 'איזו מהמילים היא בעלת משמעות דומה ל-"טפרים"?',
    promptEn: 'Which has a similar meaning to "claws"?',
    options: ['רגליים', 'תפרים', 'ציפורניים', 'טיפות'],
    optionsEn: ['Legs', 'Stitches', 'Nails', 'Drops'],
    correct: 2,
    explanation: 'טפרים = ציפורניים חדות של חיות טרף. תפרים זה משהו אחר לגמרי.',
    explanationEn: '"Claws" are the sharp nails of predatory animals. "Stitches" is something else entirely.',
    guidance: 'נרדפות: שים לב למילים שנשמעות דומה.',
    guidanceEn: 'Synonyms: watch out for similar-sounding words.',
    dir: 'rtl',
  },
  {
    id: 'e4-v2',
    category: 'verbal',
    prompt: 'איזה זוג מילים אינו של נרדפות?',
    promptEn: 'Which pair is NOT synonyms?',
    options: ['גדול / ענק', 'שמח / מאושר', 'יפה / מקסים', 'קר / חם'],
    optionsEn: ['Big / huge', 'Happy / joyful', 'Pretty / lovely', 'Cold / hot'],
    correct: 3,
    explanation: 'קר וחם הם הפכים, לא נרדפות.',
    explanationEn: 'Cold and hot are opposites, not synonyms.',
    guidance: 'נרדפות = משמעות דומה. הפכים = משמעות נגדית.',
    guidanceEn: 'Synonyms = similar meaning. Opposites = contrary meaning.',
    dir: 'rtl',
  },
  {
    id: 'e4-v3',
    category: 'verbal',
    prompt: 'מה ההפך של "להלהיט"?',
    promptEn: 'What is the opposite of "to ignite/excite"?',
    options: ['להשליך', 'להשתיק', 'לשכך', 'לשתף'],
    optionsEn: ['To throw', 'To silence', 'To calm down', 'To share'],
    correct: 2,
    explanation: 'להלהיט = לעורר התלהבות. ההיפך הוא לשכך = להרגיע, להוריד את העוצמה.',
    explanationEn: '"Ignite/excite" = stir up enthusiasm. Opposite is "calm down" = soothe, reduce intensity.',
    guidance: 'הפכים: חשוב על המשמעות וחפש את הפעולה ההפוכה.',
    guidanceEn: 'Opposites: think of the meaning and find the reverse action.',
    dir: 'rtl',
  },
  {
    id: 'e4-v4',
    category: 'verbal',
    prompt: 'איזו מילה אינה משתייכת לקבוצה: תפוז, אגס, תפוח, גזר?',
    promptEn: 'Which does not belong: orange, pear, apple, carrot?',
    options: ['תפוז', 'אגס', 'תפוח', 'גזר'],
    optionsEn: ['Orange', 'Pear', 'Apple', 'Carrot'],
    correct: 3,
    explanation: 'תפוז, אגס ותפוח הם פירות. גזר הוא ירק.',
    explanationEn: 'Orange, pear and apple are fruits. Carrot is a vegetable.',
    guidance: 'מצא את הקטגוריה של הרוב, וחפש מי לא שייך אליה.',
    guidanceEn: 'Find the majority category and the one that doesn\'t fit.',
    dir: 'rtl',
  },
  {
    id: 'e4-m1',
    category: 'math',
    prompt: 'יוסי שוקל 64 ק"ג. ענבל אחותו הקטנה שוקלת 32 ק"ג. כמה ממשקלו של יוסי מהווה משקלה של ענבל?',
    promptEn: 'Yossi weighs 64 kg. His little sister Inbal weighs 32 kg. What fraction of Yossi\'s weight is Inbal?',
    options: ['חצי', 'שליש', 'רבע', 'שלושה רבעים'],
    optionsEn: ['Half', 'Third', 'Quarter', 'Three quarters'],
    correct: 0,
    explanation: '32 הוא חצי מ-64.',
    explanationEn: '32 is half of 64.',
    guidance: 'בעיית שברים: בדוק מהו היחס בין שני המספרים.',
    guidanceEn: 'Fraction problem: find the ratio between the two numbers.',
    dir: 'rtl',
  },
  {
    id: 'e4-m2',
    category: 'math',
    prompt: 'במבחן בחשבון כל תשובה נכונה מזכה ב-½ נקודה. כמה נקודות מקבל מי שענה נכון על 10 שאלות?',
    promptEn: 'In a math test, each correct answer is worth ½ a point. How many points for 10 correct answers?',
    options: ['5', '10', '20', '15'],
    correct: 0,
    explanation: '10 שאלות × ½ נקודה = 5 נקודות.',
    explanationEn: '10 questions × ½ point = 5 points.',
    guidance: 'כפל בשבר: כפול ב-½ זה כמו לחלק ב-2.',
    guidanceEn: 'Multiplying by ½ is the same as dividing by 2.',
    dir: 'rtl',
  },
  {
    id: 'e4-m3',
    category: 'math',
    prompt: 'רוני ולטל אספו ביחד מדבקות. רוני הביאה 35, ולטל הביאה 32. באוסף שלהן יש 42 מדבקות זוהרות. כמה מדבקות שאינן זוהרות יש להן?',
    promptEn: 'Roni and Lital pooled stickers. Roni: 35, Lital: 32. They have 42 shiny stickers. How many non-shiny stickers?',
    options: ['25', '67', '109', '32'],
    correct: 0,
    explanation: 'סה"כ: 35+32=67. לא זוהרות: 67-42=25.',
    explanationEn: 'Total: 35+32=67. Non-shiny: 67-42=25.',
    guidance: '2 שלבים: קודם חבר את הכל, אז חסר את החלק שאתה יודע.',
    guidanceEn: '2 steps: first add everything, then subtract the known part.',
    dir: 'rtl',
  },
  {
    id: 'e4-m4',
    category: 'math',
    prompt: 'מהו המספר שאם נחסיר ממנו 2 ונכפיל ב-5 נקבל 25?',
    promptEn: 'What number, when you subtract 2 and multiply by 5, gives 25?',
    options: ['7', '6', '9', '4'],
    correct: 0,
    explanation: '25 ÷ 5 = 5. 5 + 2 = 7. בדיקה: (7-2) × 5 = 25 ✓',
    explanationEn: '25 ÷ 5 = 5. 5 + 2 = 7. Check: (7-2) × 5 = 25 ✓',
    guidance: 'בעיה הפוכה: בצע את הפעולות מהסוף להתחלה — קודם חלק ב-5, ואז הוסף 2.',
    guidanceEn: 'Reverse problem: do operations backwards — first divide by 5, then add 2.',
    dir: 'rtl',
  },
  {
    id: 'e4-s1',
    category: 'shapes',
    prompt: 'סדרה: 🟢 🟢🟡 🟢🟡🔵 ?\n\nמה הקבוצה הבאה?',
    promptEn: 'Sequence: 🟢 🟢🟡 🟢🟡🔵 ?\n\nWhat\'s next?',
    options: ['🟢🟡🔵🔴', '🟢🟢🟢', '🔴', '🟢🟡'],
    correct: 0,
    explanation: 'בכל קבוצה מוסיפים צבע חדש. הבא: הוספת אדום.',
    explanationEn: 'Each group adds a new color. Next: add red.',
    guidance: 'דפוס מתרחב: מה מתווסף בכל פעם?',
    guidanceEn: 'Expanding pattern: what gets added each time?',
    dir: 'rtl',
  },
  {
    id: 'e4-s2',
    category: 'shapes',
    prompt: 'סדרה: ⬛ ⬛⬜ ⬜⬛ ⬛⬜?\n\nמה הקבוצה הבאה?',
    promptEn: 'Sequence: ⬛ ⬛⬜ ⬜⬛ ⬛⬜?\n\nWhat\'s next?',
    options: ['⬜⬛', '⬛⬛', '⬜⬜', '⬛'],
    correct: 0,
    explanation: 'הדפוס מתחלף: ⬛⬜ ואז ⬜⬛ לסירוגין.',
    explanationEn: 'Pattern alternates: ⬛⬜ then ⬜⬛.',
    guidance: 'שים לב לסדר הצבעים בתוך כל זוג.',
    guidanceEn: 'Notice the color order within each pair.',
    dir: 'rtl',
  },
];

// =============================================================
// Exam 5 — Logic & speed
// =============================================================
const EXAM_5_QUESTIONS: ExamQ[] = [
  {
    id: 'e5-v1',
    category: 'verbal',
    prompt: 'איזה חודש הוא החודש השלישי לפי לוח השנה הגרגוריאני?',
    promptEn: 'Which month is the third in the Gregorian calendar?',
    options: ['ינואר', 'דצמבר', 'ספטמבר', 'מרץ'],
    optionsEn: ['January', 'December', 'September', 'March'],
    correct: 3,
    explanation: 'ינואר=1, פברואר=2, מרץ=3.',
    explanationEn: 'January=1, February=2, March=3.',
    guidance: 'ספור את החודשים מינואר.',
    guidanceEn: 'Count months from January.',
    dir: 'rtl',
  },
  {
    id: 'e5-v2',
    category: 'verbal',
    prompt: 'צורתה של איזו מדינה היא מגף?',
    promptEn: 'Which country is shaped like a boot?',
    options: ['יוון', 'ישראל', 'ירדן', 'איטליה'],
    optionsEn: ['Greece', 'Israel', 'Jordan', 'Italy'],
    correct: 3,
    explanation: 'איטליה ידועה בצורת המגף שלה במפה.',
    explanationEn: 'Italy is famous for its boot-shaped outline on the map.',
    guidance: 'ידע על מפת העולם.',
    guidanceEn: 'World map knowledge.',
    dir: 'rtl',
  },
  {
    id: 'e5-v3',
    category: 'verbal',
    prompt: 'איזו מילה משלימה את המשפט: "טליה הביאה לבית הספר את ____ שלה."',
    promptEn: 'Which word completes: "Talia brought her ____ to school."',
    options: ['פיל', 'מחברת', 'בית', 'גשר'],
    optionsEn: ['Elephant', 'Notebook', 'House', 'Bridge'],
    correct: 1,
    explanation: 'מחברת היא הדבר היחיד מהאופציות שמגיוני להביא לבית הספר.',
    explanationEn: 'A notebook is the only option that makes sense to bring to school.',
    guidance: 'השלם משפט: בחר את האופציה שהכי הגיונית בהקשר.',
    guidanceEn: 'Complete the sentence: choose the most logical option for the context.',
    dir: 'rtl',
  },
  {
    id: 'e5-v4',
    category: 'verbal',
    prompt: 'איזה מהמושגים יוצא דופן במשמעותו?',
    promptEn: 'Which expression is the odd one out by meaning?',
    options: ['אחד בפה ואחד בלב', 'פיו וליבו אינם שווים', 'אין כוחו אלא בפיו', 'אין תוכו כברו'],
    optionsEn: ['One thing in mouth, another in heart', 'Mouth and heart are not equal', 'His power is only in his words', 'His inside is not like his outside'],
    correct: 2,
    explanation: '3 ביטויים מתארים אדם צבוע. "אין כוחו אלא בפיו" מתאר אדם שמדבר הרבה אבל לא עושה.',
    explanationEn: '3 idioms describe a hypocrite. "His power is only in words" describes someone who talks but doesn\'t act.',
    guidance: 'ביטויים: חפש את המשמעות העמוקה של כל אחד וזהה את החריג.',
    guidanceEn: 'Idioms: look for the deeper meaning of each and find the exception.',
    dir: 'rtl',
  },
  {
    id: 'e5-m1',
    category: 'math',
    prompt: 'בחצר של דורון יש 3 עצי דובדבן. מכל עץ נושרים 10 עלים בכל יום. כמה עלים יאסוף ביומיים?',
    promptEn: 'Doron has 3 cherry trees. 10 leaves fall from each per day. How many in 2 days?',
    options: ['90', '15', '30', '60'],
    correct: 3,
    explanation: '3 עצים × 10 עלים = 30 ליום. ביומיים: 30 × 2 = 60.',
    explanationEn: '3 trees × 10 leaves = 30/day. 2 days: 30 × 2 = 60.',
    guidance: '2 שלבי כפל: עצים × עלים, ואז × ימים.',
    guidanceEn: '2-step multiplication: trees × leaves, then × days.',
    dir: 'rtl',
  },
  {
    id: 'e5-m2',
    category: 'math',
    prompt: 'בכיתה היו 25 ילדים. הגיעו עוד 8 ילדים, ואז 11 הלכו הביתה. כמה ילדים נשארו בכיתה?',
    promptEn: 'A class had 25 kids. 8 more arrived, then 11 went home. How many remain?',
    options: ['22', '33', '20', '14'],
    correct: 0,
    explanation: '25+8=33. 33-11=22.',
    explanationEn: '25+8=33. 33-11=22.',
    guidance: 'קודם הוסף, ואחר כך חסר.',
    guidanceEn: 'First add, then subtract.',
    dir: 'rtl',
  },
  {
    id: 'e5-m3',
    category: 'math',
    prompt: 'לעידן יש 15 נחשי גומי, 13 דובוני גומי ו-12 בננות גומי. הוא ערבב את הכל ושם בשקיות, כך שבכל שקית 4 ממתקים. בכמה שקיות השתמש?',
    promptEn: "Idan has 15 gummy snakes, 13 gummy bears, and 12 gummy bananas. He mixed and bagged 4 candies per bag. How many bags?",
    options: ['10', '20', '8', '5'],
    correct: 0,
    explanation: '15+13+12=40. 40÷4=10 שקיות.',
    explanationEn: '15+13+12=40. 40÷4=10 bags.',
    guidance: 'קודם חבר את הכל, ואז חלק במספר ממתקים בשקית.',
    guidanceEn: 'First add everything, then divide by per-bag count.',
    dir: 'rtl',
  },
  {
    id: 'e5-m4',
    category: 'math',
    prompt: 'נועה רוצה להכין 2 כוסות מיץ תפוזים מ-6 תפוזים. אם לכל כוס דרושים 3 תפוזים, וההכנה לוקחת חצי דקה לכוס, כמה זמן ייקח לה?',
    promptEn: 'Noa wants 2 glasses of orange juice from 6 oranges. Each glass needs 3 oranges and takes half a minute. How long total?',
    options: ['60 שניות', '90 שניות', '45 שניות', '32 שניות'],
    optionsEn: ['60 sec', '90 sec', '45 sec', '32 sec'],
    correct: 0,
    explanation: '2 כוסות × ½ דקה = 1 דקה = 60 שניות.',
    explanationEn: '2 glasses × ½ minute = 1 minute = 60 seconds.',
    guidance: 'התפוזים זה הסחת דעת. מה שמעניין: כמה דקות לכל כוס × מספר כוסות.',
    guidanceEn: 'The oranges are a distractor. What matters: time per glass × number of glasses.',
    dir: 'rtl',
  },
  {
    id: 'e5-s1',
    category: 'shapes',
    prompt: 'סדרה: 🔴🔵 🔵🔴 🔴🔵 🔵🔴 ?',
    promptEn: 'Sequence: 🔴🔵 🔵🔴 🔴🔵 🔵🔴 ?',
    options: ['🔴🔵', '🔵🔴', '🔴🔴', '🔵🔵'],
    correct: 0,
    explanation: 'הדפוס מתחלף בין 🔴🔵 ל-🔵🔴. אחרי 🔵🔴 בא 🔴🔵.',
    explanationEn: 'Alternates between 🔴🔵 and 🔵🔴. After 🔵🔴 comes 🔴🔵.',
    guidance: 'דפוס סירוגי. שים לב מי בא אחרי מי.',
    guidanceEn: 'Alternating pattern. Notice who follows whom.',
    dir: 'rtl',
  },
  {
    id: 'e5-s2',
    category: 'shapes',
    prompt: 'מהו ההבדל בין: ⭐⭐⭐ ל-⭐⭐⭐⭐?',
    promptEn: "What's the difference: ⭐⭐⭐ vs ⭐⭐⭐⭐?",
    options: ['כוכב 1', 'כוכבים 2', 'כוכבים 3', 'אותו דבר'],
    optionsEn: ['1 star', '2 stars', '3 stars', 'Same'],
    correct: 0,
    explanation: '4-3=1. בקבוצה השנייה יש כוכב נוסף.',
    explanationEn: '4-3=1. The second group has one extra star.',
    guidance: 'ספור את הצורות בכל קבוצה והשווה.',
    guidanceEn: 'Count shapes in each group and compare.',
    dir: 'rtl',
  },
];

// =============================================================
// Exam catalog
// =============================================================
export const MOCK_EXAMS: MockExam[] = [
  {
    id: 'exam1',
    title: 'מבחן 1: יסודות',
    titleEn: 'Exam 1: Foundations',
    description: 'שאלות על קטגוריות, ביטויים ובעיות חיבור-חיסור',
    descriptionEn: 'Categories, idioms, and add/subtract problems',
    questions: EXAM_1_QUESTIONS,
    timeLimitSec: 25 * 60,
  },
  {
    id: 'exam2',
    title: 'מבחן 2: ידע והבנה',
    titleEn: 'Exam 2: Knowledge & Comprehension',
    description: 'גיאוגרפיה, אוצר מילים וחלוקה',
    descriptionEn: 'Geography, vocabulary, and division',
    questions: EXAM_2_QUESTIONS,
    timeLimitSec: 25 * 60,
  },
  {
    id: 'exam3',
    title: 'מבחן 3: בעיות מילוליות',
    titleEn: 'Exam 3: Word Problems',
    description: 'בעיות חשבון מילוליות וקטגוריות מקצועות',
    descriptionEn: 'Word problems and profession categories',
    questions: EXAM_3_QUESTIONS,
    timeLimitSec: 25 * 60,
  },
  {
    id: 'exam4',
    title: 'מבחן 4: אוצר מילים מתקדם',
    titleEn: 'Exam 4: Advanced Vocabulary',
    description: 'נרדפות, הפכים ושברים',
    descriptionEn: 'Synonyms, opposites, and fractions',
    questions: EXAM_4_QUESTIONS,
    timeLimitSec: 25 * 60,
  },
  {
    id: 'exam5',
    title: 'מבחן 5: לוגיקה ומהירות',
    titleEn: 'Exam 5: Logic & Speed',
    description: 'ביטויים, השלמת משפטים ובעיות מורכבות',
    descriptionEn: 'Idioms, sentence completion, and complex problems',
    questions: EXAM_5_QUESTIONS,
    timeLimitSec: 25 * 60,
  },
];

export const getMockExam = (id: string) => MOCK_EXAMS.find((e) => e.id === id) ?? MOCK_EXAMS[0];
